travis:
  secure:
    BINSTAR_TOKEN: pk4GWS4tYdXWIgrnXYU2Tt0SCYXoirOGGipnNuxiMnK3c5sLR11lnezLMpG2ArhZyrVMz+fzsTfD3aWiHgNb5sIMTPlO2T7477PhPRiqfAG2Bh6L707GumFC3HUYF+mmsBUoGLi/doDaTbQNtTfy+zVE8sHeWZ8jzOnFkB2jcsp0iZZkOMuHDmiyQ3wKUPjiwckWHMFbna9+xf4pRJ0QuMrngBzEPL0uAS69t9YlwleqwXQqEWsvyxOs0HQPbLrhIlyl6fLPicHXkKhoX6s1sxXy/Gcw88QlDqUbx719t4DK4eyBnOC0o+dXwTZgZEyxdWvTItsJ2qcoBJfxmtlYwW6uPZemBD9Yz4C4GFj701N7XZeSJoipDiZp7ij66xSWOm5BqqLJe/yoiHAcGpWkWWZl8RoqTiKN2zNdgDOgdYp/9BA6Px1HHyZfApguIRLQUqI5NnqiRkNYaW8r8nAwr+0uY3PE6wORpfpvlBxcLSKQKkHJFzLWvV3XBIeU1hTXsrttOdiS//gKQOjFAZvO3x44OruM82bWLlzxWe/FidKm3gniCc40pve/GBcpsfxGt2o2lOEWy9riVXEMVpZ+HXG8tGFsvg5P2eBxWJPSTsCSQvZLnR3wr7m3OBGmtvEtzyDvzX5XYJnjMNfo33tltFXeMpIfQ2Qhts2N8gSwmgc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
