travis:
  secure:
    BINSTAR_TOKEN: pu/7/5zCuf1MCFb7SpNujJO1goo7783jMQJIPGC/r4gagnWI09T2BLCHVsxO7UsDBXcVdBsq8xRMLx2z5QyqDf5yHJqm1AE59PTLjb+Dr1m6cMmlXKVNbvA7CRFW+PZWMwHp1I0DCXKrrhw40wWuiv9LCPyTXpCuPvLqWUleJMzW8EU2asjKyUpbF057VqQQdznYBS73Mzt6bzXaJoCP2lYRQq1EYhbsBqY22ueXE0J7EdsyGzmhgdx/9RbASA9HcTbZrP4OK/JBXSdHRqdkE3GDhrQNt2JqJUDoImAXDqNj1A+LMpTNe1GOYBL1LmVAPkwG8eHlTyRKqSS+bY38e4y9yCW15+Ykwg3NafpiEvw0fCKGOQwr0/BnkYu1p0U4+byDeZmX49yOU2+DBDJUxNKUugalKBVo3U0ifenCEZPxTysxx+RbYpWRlBrwL/2u9ovhegjgGQxZe9zV80xSlkyI54lEJnng2iqPVSCTD8aRASCFKp3ijF6YeHgPoGbZsPVX5qj5X9dMhheo2if5AztJokfffgkWzlPPV0xJyG6VIpA0ks6k0GwaMQwLvBJB3SEbJlsGQIZFZ+8t6oUylD3AFLf1g+TXUtVm5KOa6ktykieS6vwytsCQXk3WLctrgDHiAz5WW9SF3Fb6jMeJ6ZYNhSlMKWenfcVgbLzsZsM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
